### ISSUE TITLE
Using `ruff` instead of `black`, `flake8`, ...

### ISSUE THREAD

**Issue by boidolr** [zyskarch/pytestarch#109]
Would you be interested in replacing `isort`, `black`, `flake8` and `bandit` with [`ruff`](https://github.com/astral-sh/ruff) so that there are less tools involved, and possibly more rules that could be activated?
I'd be happy to provide an initial PR.

**Comment by zyskarch** [comment]
I'm a big fan of ruff, so definitely interested! 

Please note: Due to some other commitments, I will not be able to do any meaningful work on this project within the next month (other than urgent bugfixes if necessary). So while I would glady merge a PR provided by you, it might take a couple of weeks before I have the time to review it... :)

**Comment by walidzz** [comment]
It's cool to use Ruff, but I think they didn’t implement all pylint rules. So if we need to lint our codebase using pylint rules, it will skip many checks :/
Maybe doing it later, when a major stable ruff release is available.

**Comment by zyskarch** [comment]
True, they don't support all pylint rules. But then again, pytestarch is not currently using pylint at all, so I don't think we're loosing anything by switching to ruff at the moment ...
