### ISSUE TITLE
Permit to exclude external libraries based on a regex

### ISSUE THREAD

**Issue by Lenormju** [zyskarch/pytestarch#114]
I'd like to filter out some libraries (for example the stdlib `logging`, `typing`, ... or some third-parties like `typing_extensions` ...) but not all of them.
Currently, the parameter `exclude_external_libraries` of `get_evaluable_architecture` is all-or-nothing. Also, (as documented), the parameter `exclusions` (and `regex_exclusions`) only applies to modules found in the `root_path`/`module_path`.

Would adding an `external_exclusions` be interesting ?

This would greatly help to reduce the noise when exporting the architecture graph (for manual review).
I'm currently doing :
```python
evaluable = get_evaluable_architecture(...)
import matplotlib.pyplot as plt
import networkx as nx
G: NetworkxGraph = evaluable._graph._graph
pos = nx.circular_layout(G)
plt.figure(3, figsize=(12, 12))
nx.draw(G, pos, with_labels=True)
plt.savefig("Graph.png", format="PNG", dpi=300)
```

**Comment by zyskarch** [comment]
Definitely! I'll take a look at it, thanks for the suggestion!

**Comment by Lenormju** [comment]
Okay, I'll work on it.

**Comment by zyskarch** [comment]
I'm the last person to stop you from contributing ;) However, I have started working on it already, and I'd say within the next two weeks should be a reasonable timeframe to complete it.
So if you do want to speed it up by opening a PR before then, let me know - otherwise I'll just keep working on it :)
